spring:
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: root
    password: password